#!/usr/bin/env node
/**
 * Generates infra/postgres/init/02-seed.sql with synthetic, deterministic data:
 *   - a small plan catalogue
 *   - N customers (username user_001..user_NNN, password "password123")
 *   - 1-3 invoices per customer
 *
 * Re-run with `node infra/postgres/generate-seed.mjs` to regenerate.
 * Synthetic data only — no real credentials.
 */
import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const CUSTOMER_COUNT = 50;
const PASSWORD = 'password123';
const passwordHash = createHash('sha256').update(PASSWORD).digest('hex');

const plans = [
  { id: 'mobile_basic', name: 'Mobile Basic', price: 8999.0, speed: 50 },
  { id: 'mobile_premium', name: 'Mobile Premium', price: 14999.0, speed: 150 },
  { id: 'fiber_300mb', name: 'Fiber 300', price: 19999.0, speed: 300 },
  { id: 'fiber_600mb', name: 'Fiber 600', price: 25999.99, speed: 600 },
  { id: 'fiber_1000mb', name: 'Fiber 1000', price: 32999.0, speed: 1000 },
];

const sql = (v) => String(v).replace(/'/g, "''");
const lines = [];
lines.push('-- AUTO-GENERATED by infra/postgres/generate-seed.mjs. Do not edit by hand.');
lines.push('-- Synthetic data only. All passwords are "password123".');
lines.push('');

lines.push('INSERT INTO plans (plan_id, name, price, speed_mbps) VALUES');
lines.push(
  plans.map((p) => `  ('${p.id}', '${sql(p.name)}', ${p.price}, ${p.speed})`).join(',\n') +
    '\nON CONFLICT (plan_id) DO NOTHING;',
);
lines.push('');

const customerValues = [];
const invoiceValues = [];

for (let i = 1; i <= CUSTOMER_COUNT; i++) {
  const idx = String(i).padStart(3, '0');
  const customerId = `customer_${idx}`;
  const username = `user_${idx}`;
  const plan = plans[i % plans.length];
  const segment = i % 7 === 0 ? 'business' : 'consumer';
  customerValues.push(`  ('${customerId}', '${username}', '${passwordHash}', '${segment}', '${plan.id}')`);

  const invoiceCount = (i % 3) + 1; // 1..3
  for (let j = 1; j <= invoiceCount; j++) {
    const invoiceId = `inv_${idx}_${j}`;
    const status = j === 1 ? 'pending' : j === 2 ? 'overdue' : 'paid';
    const dueDay = String(((i + j) % 27) + 1).padStart(2, '0');
    const dueDate = `2026-07-${dueDay}`;
    invoiceValues.push(`  ('${invoiceId}', '${customerId}', ${plan.price}, '${status}', '${dueDate}')`);
  }
}

lines.push('INSERT INTO customers (customer_id, username, password_hash, segment, current_plan_id) VALUES');
lines.push(customerValues.join(',\n') + '\nON CONFLICT (customer_id) DO NOTHING;');
lines.push('');

lines.push('INSERT INTO invoices (invoice_id, customer_id, amount, status, due_date) VALUES');
lines.push(invoiceValues.join(',\n') + '\nON CONFLICT (invoice_id) DO NOTHING;');
lines.push('');

writeFileSync(join(here, 'init', '02-seed.sql'), lines.join('\n'));
console.log(
  `Wrote init/02-seed.sql: ${plans.length} plans, ${CUSTOMER_COUNT} customers, ${invoiceValues.length} invoices.`,
);
console.log(`password_hash(${PASSWORD}) = ${passwordHash}`);
