#!/usr/bin/env node
// Executive Markdown report — single k6 run vs SLO targets.
//
// Usage:
//   node scripts/generate-report.js <summary.json> [--profile <name>]
//   node scripts/generate-report.js tests/k6/reports/smoke-summary.json --profile smoke
//
// Reads a k6 --summary-export JSON and prints a Markdown report to stdout.
// Pipe to a file to commit it:
//   node scripts/generate-report.js ... > tests/k6/reports/latest-report.md

import { readFileSync } from 'fs';
import { execSync } from 'child_process';

const SLO = {
  login:          { p95Ms: 600,  errorRate: 0.01 },
  invoice_lookup: { p95Ms: 800,  errorRate: 0.01 },
  plan_change:    { p95Ms: 1200, errorRate: 0.015 },
  payment:        { p95Ms: 1500, errorRate: 0.01 },
};
const GLOBAL_SLO_P95_MS    = 1200;
const GLOBAL_SLO_ERR_RATE  = 0.01;
const GLOBAL_SLO_CHECKS    = 0.99;

const JOURNEYS = Object.keys(SLO);

// ---------- CLI args ---------------------------------------------------
const args = process.argv.slice(2);
const profileIdx = args.indexOf('--profile');
const profileName = profileIdx !== -1 ? args[profileIdx + 1] : 'unknown';
const files = args.filter((a, i) => !a.startsWith('--') && args[i - 1] !== '--profile');

if (files.length !== 1) {
  console.error('Usage: node generate-report.js <summary.json> [--profile <name>]');
  process.exit(2);
}

// ---------- Load summary ----------------------------------------------
const raw = JSON.parse(readFileSync(files[0], 'utf8'));
const m   = raw.metrics ?? {};

const globalP95  = m['http_req_duration']?.['p(95)']  ?? null;
const globalErr  = m['http_req_failed']?.['value']     ?? null;
const globalChk  = m['checks']?.['value']              ?? null;

function journeyP95(j) {
  return m[`http_req_duration{journey:${j}}`]?.['p(95)'] ?? null;
}

// ---------- Git metadata (best-effort) --------------------------------
function gitMeta() {
  try {
    const sha     = execSync('git rev-parse --short HEAD', { stdio: ['pipe','pipe','pipe'] }).toString().trim();
    const branch  = execSync('git rev-parse --abbrev-ref HEAD', { stdio: ['pipe','pipe','pipe'] }).toString().trim();
    return `\`${branch}@${sha}\``;
  } catch {
    return '_unavailable_';
  }
}

// ---------- Format helpers -------------------------------------------
function fmtMs(v)  { return v == null ? 'N/A' : `${v.toFixed(0)} ms`; }
function fmtPct(v) { return v == null ? 'N/A' : `${(v * 100).toFixed(2)}%`; }

function statusEmoji(passing) { return passing ? '✅' : '🔴'; }

function journeyRow(journey, slo) {
  const p95  = journeyP95(journey);
  const name = journey.replace(/_/g, ' ');
  const p95ok = p95 != null ? p95 < slo.p95Ms : null;
  return `| ${name} | < ${slo.p95Ms} ms | ${fmtMs(p95)} | ${p95ok == null ? '⚪' : statusEmoji(p95ok)} |`;
}

// ---------- Threshold decode -----------------------------------------
// k6 summary-export encodes threshold results as `false` = passed, `true` = failed.
// The key is the metric expression; value is a bool.
function thresholdFailed(expr) {
  const t = raw.metrics?.[expr]?.thresholds;
  if (!t) return null;
  // First threshold value (e.g. { 'p(95)<600': false })
  return Object.values(t).some(v => v === true);
}

const globalP95Fail  = thresholdFailed('http_req_duration');
const globalErrFail  = thresholdFailed('http_req_failed');
const globalChkFail  = thresholdFailed('checks');

const journeyFails = Object.fromEntries(
  JOURNEYS.map(j => [j, thresholdFailed(`http_req_duration{journey:${j}}`)])
);

const overallPass = [globalP95Fail, globalErrFail, globalChkFail, ...Object.values(journeyFails)]
  .every(f => f === false || f === null);

const overallEmoji = overallPass ? '✅ PASSED' : '🔴 FAILED';

// ---------- Build report ----------------------------------------------
const now = new Date().toISOString();

const report = `# k6 Performance Report — ${profileName}

| | |
|---|---|
| **Profile** | ${profileName} |
| **Generated** | ${now} |
| **Commit** | ${gitMeta()} |
| **Overall** | **${overallEmoji}** |

---

## Global SLOs

| Metric | Target | Result | Status |
|---|---|---|---|
| p95 latency | < ${GLOBAL_SLO_P95_MS} ms | ${fmtMs(globalP95)} | ${globalP95 != null ? statusEmoji(globalP95 < GLOBAL_SLO_P95_MS) : '⚪'} |
| Error rate | < ${fmtPct(GLOBAL_SLO_ERR_RATE)} | ${fmtPct(globalErr)} | ${globalErr != null ? statusEmoji(globalErr < GLOBAL_SLO_ERR_RATE) : '⚪'} |
| Checks pass rate | > ${fmtPct(GLOBAL_SLO_CHECKS)} | ${fmtPct(globalChk)} | ${globalChk != null ? statusEmoji(globalChk > GLOBAL_SLO_CHECKS) : '⚪'} |

## Per-Journey p95 vs SLO

| Journey | SLO | p95 | Status |
|---|---|---|---|
${JOURNEYS.map(j => journeyRow(j, SLO[j])).join('\n')}

---

> Generated by \`scripts/generate-report.js\`.
> Reproduce: \`make ${profileName}\` then \`node scripts/generate-report.js tests/k6/reports/${profileName}-summary.json --profile ${profileName}\`
`;

process.stdout.write(report);
